global_var:
  service_name: kamco
  root_dir: /home/upload/user/kamco_doc
  app_dir: /home/chatsam-app/app
  user_id: admin

  log_level: 10
  log_detail: false

  # # 본사 내부용
  # etl_url: http://ewl-app.ewl.svc.cluster.local:8000/api/v1
  # 외부용(config 계정 수정해야함)
  etl_url: https://demo-ewl.agilesoda.ai/api/v1
